GET http://localhost:8080/oslc
Accept: application/rdf+xml

###
GET http://localhost:8080/oslc/meetingservice
Accept: application/rdf+xml

###
GET http://localhost:8080/oslc/userservice
Accept: application/rdf+xml

###
GET http://localhost:8080/users/login/jbed
Accept: application/json

<> 2024-01-13T235954.200.json
<> 2024-01-13T235833.200.jsongit 
###
GET http://localhost:8080/users?search=a
Accept: application/json

###
GET http://localhost:8080/users/id/8fad63fb-f729-455d-b5cd-ae26b8e05b7b
Accept: application/json

###
GET http://localhost:8080/meetings/user/Carlitos
Accept: application/json

<> 2024-01-13T235956.200.json
<> 2024-01-13T235840.404.json


###
GET http://localhost:8080/meetings/27ab5d11-cb37-4d08-a546-e1cd44ecc6d8/proposals
Accept: application/json

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "login": "nole24",
  "fullName": "Novak Djokovic",
  "email": "djoker.nole@atp.eu",
  "timezone": "UTC+0",
  "password": "djokerNole24"
}

###
GET http://localhost:8080/meetings/27ab5d11-cb37-4d08-a546-e1cd44ecc6d8/participations
Accept: application/json

###
POST http://localhost:8080/meetings/27ab5d11-cb37-4d08-a546-e1cd44ecc6d8/participations
Content-Type: application/json

{
  "userId": "8fhd63fb-f729-455d-b5cd-ae26b8e05b7b"
}

###
POST http://localhost:8080/meetings/b9d2765a-eecb-45e4-9f92-8333813266aa/participations
Content-Type: application/json

{
  "userId": "8fhd63fb-f729-455d-b5cd-ae26b8e05b7b"
}

###

###
GET http://localhost:8080/meetings/7c2f9193-c6bc-4511-adc8-6d0573d1ca39
Accept: application/json

###
###
GET http://localhost:8080/meetings/7c2f9193-c6bc-4511-adc8-6d0573d1ca39/proposals
Accept: application/json

###